package onekr.commonservice.biz;

public enum ConfigOwner {
	
	SYSTEM_EMAIL_SERVER,
	SYSTEM_EMAIL_PORT,
	SYSTEM_EMAIL_USERNAME,
	SYSTEM_EMAIL_PASSWORD,
	SYSTEM_EMAIL_DEFAULTENCODING,
	SYSTEM_EMAIL_SMTP_AUTH;
}
